name: Update Shadowrocket Rules

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output
          git commit -m "Auto update Shadowrocket conf" || exit 0
          git push
